name: Update Binary

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  lahaina:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚"
      - name: 拉取 action_build_lahaina_system
        uses: actions/checkout@v5.0.0
        with:
          repository: Human-Machine-Matrix/action_build_lahaina_system
          token: ${{ secrets.GH_TOKEN }}
          path: action_build_lahaina_system
          submodules: recursive
          fetch-depth: 0
      - name: 提交 action_build_lahaina_system
        run: |
          cd action_build_lahaina_system
          git submodule update --remote --merge
          git commit -am "更新 Binary" || echo "无需更新 Binary"
          git push origin main
  
  taro:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚"
      - name: 拉取 action_build_taro_system
        uses: actions/checkout@v5.0.0
        with:
          repository: Human-Machine-Matrix/action_build_taro_system
          token: ${{ secrets.GH_TOKEN }}
          path: action_build_taro_system
          submodules: recursive
          fetch-depth: 0
      - name: 提交 action_build_taro_system
        run: |
          cd action_build_taro_system
          git submodule update --remote --merge
          git commit -am "更新 Binary" || echo "无需更新 Binary"
          git push origin main

  kalama:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚"
      - name: 拉取 action_build_kalama_system
        uses: actions/checkout@v5.0.0
        with:
          repository: Human-Machine-Matrix/action_build_kalama_system
          token: ${{ secrets.GH_TOKEN }}
          path: action_build_kalama_system
          submodules: recursive
          fetch-depth: 0
      - name: 提交 action_build_kalama_system
        run: |
          cd action_build_kalama_system
          git submodule update --remote --merge
          git commit -am "更新 Binary" || echo "无需更新 Binary"
          git push origin main

  PayloadToFlash:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚"
      - name: 拉取 PayloadToFlash
        uses: actions/checkout@v5.0.0
        with:
          repository: Human-Machine-Matrix/PayloadToFlash
          token: ${{ secrets.GH_TOKEN }}
          path: PayloadToFlash
          submodules: recursive
          fetch-depth: 0
      - name: 提交 PayloadToFlash
        run: |
          cd PayloadToFlash
          git submodule update --remote --merge
          git commit -am "更新 Binary" || echo "无需更新 Binary"
          git push origin main

  PCEngine_Check:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚"
      - name: 拉取 PCEngine_Check
        uses: actions/checkout@v5.0.0
        with:
          repository: Human-Machine-Matrix/PCEngine_Check
          token: ${{ secrets.GH_TOKEN }}
          path: PCEngine_Check
          submodules: recursive
          fetch-depth: 0
      - name: 提交 PCEngine_Check
        run: |
          cd PCEngine_Check
          git submodule update --remote --merge
          git commit -am "更新 Binary" || echo "无需更新 Binary"
          git push origin main

  rubens:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚"
      - name: 拉取 action_build_rubens_system
        uses: actions/checkout@v5.0.0
        with:
          repository: Human-Machine-Matrix/action_build_rubens_system
          token: ${{ secrets.GH_TOKEN }}
          path: action_build_rubens_system
          submodules: recursive
          fetch-depth: 0
      - name: 提交 action_build_rubens_system
        run: |
          cd action_build_rubens_system
          git submodule update --remote --merge
          git commit -am "更新 Binary" || echo "无需更新 Binary"
          git push origin main
